const test=require('node:test'),assert=require('node:assert/strict');
const base='../main/assets/',U=require(base+'phase7_labs/ucs-engine.js'),A=require(base+'phase7_labs/astar-engine.js'),I=require(base+'phase7_labs/iddfs-engine.js'),G=require(base+'phase7_labs/graphs.js'),W=require(base+'phase7_labs/weighted-core.js'),S=require(base+'search_labs/engines.js');
function finish(e,check=()=>{}){let s=e.snapshot(),i=0;while(!s.done&&i++<100000){s=e.step();check(s)}assert.ok(s.done,'Search must terminate');return s}
function graph(ids,edges,directed=true){return {nodes:ids.split('').map((id,i)=>({id,x:i*20,y:i%2*50,h:0})),edges,directed,adj:S.adjacency(edges,directed)}}
function oracle(g,start){const d=Object.fromEntries(g.nodes.map(n=>[n.id,Infinity]));d[start]=0;const edges=g.directed?g.edges:[...g.edges,...g.edges.map(([a,b,w])=>[b,a,w])];for(let i=0;i<g.nodes.length-1;i++)for(const [a,b,w]of edges)d[b]=Math.min(d[b],d[a]+w);return d}
function pathCost(g,path){return path.slice(1).reduce((sum,n,i)=>sum+Math.min(...g.edges.filter(e=>(e[0]===path[i]&&e[1]===n)||(!g.directed&&e[1]===path[i]&&e[0]===n)).map(e=>e[2])),0)}
test('UCS follows g priority, decreases unique queue entries and settles goal only on pop',()=>{const g=graph('SABG',[['S','G',20],['S','A',5],['S','B',1],['B','A',1],['A','G',2]]),e=U.engine(g,'S','G');let generated=false,decreased=false;const s=finish(e,t=>{assert.equal(new Set(t.open.map(x=>x.node)).size,t.open.length);for(let i=1;i<t.open.length;i++)assert.ok(t.open[i].g>=t.open[i-1].g);if(t.goalCost===20&&t.current!=='G'){generated=true;assert.equal(t.done,false);assert.equal(t.found,false)}if(t.operation==='decrease'&&t.changed==='A'){decreased=true;assert.equal(t.parent.A,'B');assert.equal(t.g.A,2)}});assert.ok(generated&&decreased);assert.deepEqual(s.path,['S','B','A','G']);assert.equal(s.goalCost,4);assert.equal(pathCost(g,s.path),4);assert.deepEqual(s.expanded,['S','B','A','G']);assert.equal(U.engine(g,'S','G').snapshot().g.A,Infinity)});
test('UCS validates negative/non-finite costs and handles zero edges, parallel edges and unreachable goals',()=>{for(const w of [-1,NaN,Infinity])assert.throws(()=>U.engine(graph('AB',[['A','B',w]]),'A','B'),/non-negative/);const g=graph('ABCG',[['A','B',5],['A','B',0],['B','C',0],['C','B',0],['C','G',2]]);assert.equal(finish(U.engine(g,'A','G')).goalCost,2);const same=finish(U.engine(g,'A','A'));assert.deepEqual(same.path,['A']);assert.equal(same.goalCost,0);const none=finish(U.engine(graph('ABG',[['A','B',1]]),'A','G'));assert.equal(none.found,false);assert.equal(none.phase,'failure')});
test('UCS and A* with zero heuristic match Bellman-Ford across weighted graphs and every node pair',()=>{let seed=91;const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/2**32};for(let trial=0;trial<10;trial++){const edges=[];for(let a=0;a<6;a++)for(let b=a+1;b<6;b++)if(random()<.45)edges.push([String.fromCharCode(65+a),String.fromCharCode(65+b),Math.floor(random()*8)]);const g=graph('ABCDEF',edges,trial%2===0),h=Object.fromEntries(g.nodes.map(n=>[n.id,0]));for(const start of 'ABCDEF'){const expected=oracle(g,start);for(const goal of 'ABCDEF'){const u=finish(U.engine(g,start,goal)),a=finish(A.engine(g,start,goal,h));assert.equal(u.goalCost,expected[goal]);assert.equal(a.goalCost,u.goalCost);assert.deepEqual(a.expanded,u.expanded);assert.deepEqual(a.path,u.path);if(u.found)assert.equal(pathCost(g,u.path),u.goalCost)}}}});
test('A* uses g+h, updates parents, reopens closed nodes with an inconsistent admissible heuristic',()=>{const g=graph('SABG',[['S','A',3],['S','B',1],['B','A',1],['A','G',10],['B','G',20]]),h={S:0,A:0,B:10,G:0};let reopened=false;const s=finish(A.engine(g,'S','G',h),t=>{for(const n of g.nodes)assert.equal(t.f[n.id],t.g[n.id]+h[n.id]);for(let i=1;i<t.open.length;i++)assert.ok(t.open[i].f>=t.open[i-1].f);if(t.operation==='reopen'){reopened=true;assert.equal(t.changed,'A');assert.ok(!t.closed.includes('A'));assert.equal(t.parent.A,'B')}});assert.ok(reopened);assert.deepEqual(s.expanded,['S','A','B','A','G']);assert.equal(s.goalCost,12);assert.deepEqual(s.path,['S','B','A','G']);assert.throws(()=>A.engine(g,'S','G',{...h,G:1}),/goal heuristic/)});
test('All displayed A* heuristics are admissible for every selectable goal and find optimal paths',()=>{for(const preset of ['reference','disconnected','ucs']){const g=G.weighted(preset==='ucs'?'ucs':'astar',preset);for(const goal of g.nodes.map(n=>n.id)){const toGoal=oracle(g,goal);for(const mode of ['predefined','euclidean','manhattan','zero']){const h=G.heuristics(g,goal,mode);assert.equal(h[goal],0);for(const n of g.nodes)assert.ok(h[n.id]<=toGoal[n.id]+1e-9,`${mode} overestimates ${n.id}→${goal}`);for(const [a,b,w]of g.edges)assert.ok(Math.abs(h[a]-h[b])<=w+1e-9);const s=finish(A.engine(g,'A',goal,h));assert.equal(s.goalCost,oracle(g,'A')[goal]);if(s.found)assert.equal(pathCost(g,s.path),s.goalCost)}}}assert.equal(finish(U.engine(G.weighted('ucs'))).goalCost,6);assert.equal(finish(A.engine(G.weighted('astar'),'A','G',G.heuristics(G.weighted('astar'),'G'))).goalCost,8)});
test('IDDFS visits limits 0,1,2,3 in stable order, retains history and finds the shallowest goal',()=>{const g=G.tree(),e=I.engine(g,'A','K',4),phases=new Set();const s=finish(e,t=>{phases.add(t.phase);assert.ok(t.stack.every(f=>f.depth<=t.limit));assert.ok(t.limit<=4)});assert.equal(s.limit,3);assert.deepEqual(s.path,['A','B','E','K']);assert.deepEqual(s.history.map(r=>r.limit),[0,1,2,3]);assert.deepEqual(s.history.slice(0,3).map(r=>r.visited),[1,3,7]);assert.deepEqual(s.history[2].order,['A','B','D','E','C','F','G']);for(const p of ['start','visit','push','limit','backtrack','iteration','increase','restart','goal'])assert.ok(phases.has(p),p);assert.deepEqual(I.engine(g,'A','K',4).snapshot().visited,[]);assert.equal(I.engine(g,'A','K',4).snapshot().limit,0)});
test('IDDFS path-based cycle checks allow a later shorter visit after an earlier depth cutoff',()=>{const g=graph('SAXB G'.replace(/ /g,''),[['S','A',1],['A','X',1],['X','B',1],['S','X',1],['B','G',1],['B','S',1]]);const s=finish(I.engine(g,'S','G',5));assert.equal(s.path.length-1,3);assert.deepEqual(s.path,['S','X','B','G']);assert.equal(s.limit,3);assert.ok(s.history[3].order.filter(n=>n==='X').length>=2);const ref=S.bfs(g.adj,'S','G');assert.equal(finish(ref).path.length,s.path.length)});
test('IDDFS respects maximum depth, handles start=goal and cycles, and uses a reproducible step timeline',()=>{const g=G.tree('cyclic');const a=finish(I.engine(g,'A','K',2));assert.equal(a.found,false);assert.equal(a.limit,2);assert.equal(a.history.length,3);assert.equal(finish(I.engine(g,'A','A',0)).path.length,1);assert.equal(finish(I.engine(G.tree('disconnected'),'A','O',4)).found,false);const first=I.engine(g,'A','K',4),second=I.engine(g,'A','K',4);let s=first.snapshot();while(!s.done){s=first.step();assert.deepEqual(second.step(),s)}assert.throws(()=>I.engine(g,'A','K',-1));assert.throws(()=>I.engine(g,'A','K',2.5))});
