const test=require('node:test'),assert=require('node:assert/strict');
const base='../main/assets/',B=require(base+'phase6_labs/bayes-engine.js'),M=require(base+'phase6_labs/minimax-engine.js'),AB=require(base+'phase3_labs/alpha-beta-engine.js'),T=require(base+'phase2_labs/engines.js');
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-10,`${a} != ${b}`);
function finish(e){let s=e.snapshot(),count=0;while(!s.done&&count++<150000)s=e.step();assert.ok(s.done);return s}
function oracle(board,player,depth){const w=T.winner(board);if(w!==null)return w==='draw'?0:w===player?1:-1;if(depth===0)return 0;const values=T.legal(board).map(i=>oracle(T.move(board,i),player,depth-1));return (T.turn(board)===player?Math.max:Math.min)(...values)}
function enumerate(net,q,e){const sums=B.node(net,q).states.map(()=>0);let mass=0;for(const a of B.assignments(net,net.nodes.map(n=>n.id))){if(!Object.entries(e).every(([id,s])=>a[id]===s))continue;let p=1;for(const n of net.nodes){const row=n.cpt.find(r=>Object.entries(r.given).every(([id,s])=>a[id]===s));p*=row.p[n.states.indexOf(a[n.id])]}mass+=p;sums[B.node(net,q).states.indexOf(a[q])]+=p}return {mass,p:sums.map(p=>p/mass)}}
test('Minimax reuses alpha-beta recursion; correct alternation, terminals, cutoff and decision',()=>{
 for(const board of ['XO..X...O','XX.OO....','XXXOO....','XOXOXOOXO'])for(const player of ['X','O'])for(const depth of [1,3,9]){const cfg={board,player,depth},full=finish(M.engine(cfg)),pruned=finish(M.engine({...cfg,pruning:true}));assert.equal(full.value,oracle(board,player,depth));assert.equal(pruned.value,full.value);assert.equal(pruned.best,full.best);for(const n of full.nodes){assert.ok(n.level<=depth);if(n.type!=='Leaf'){assert.equal(n.type,(n.level%2===0)===(T.turn(board)===player)?'MAX':'MIN');assert.equal(n.value,(n.type==='MAX'?Math.max:Math.min)(...n.children.map(id=>full.nodes[id].value)))}else assert.ok(n.terminal||n.cutoff)}if(full.best!=null){const child=full.nodes[full.best];assert.equal(full.value,oracle(child.board,player,depth-1))}}
 assert.equal(M.utility('XXXOO....','X'),1);assert.equal(M.utility('OOOXX.X..','X'),-1);assert.equal(M.utility('XOXOXOOXO','X'),0);assert.notEqual(M.utility('XX.O.....','X','heuristic'),0);
 const generic=finish(M.engine({game:'generic',depth:3}));assert.equal(generic.value,finish(AB.engine({depth:3,pruning:false})).value);
});
test('Minimax exposes enter, evaluate, return, compare, backup and finish; reset has no evaluated values',()=>{const e=M.engine({depth:2}),phases=new Set();let s=e.snapshot();while(!s.done){s=e.step();phases.add(s.phase)}for(const phase of ['enter','evaluate','return','bounds','check','backup','finish'])assert.ok(phases.has(phase));const reset=M.engine({depth:2}).snapshot();assert.equal(reset.evaluated,0);assert.ok(reset.nodes.every(n=>n.value===null));assert.equal(reset.done,false)});
test('Bayesian editor rejects cycles, duplicates, self-loops; edge/state edits invalidate affected CPTs',()=>{const net=B.preset();assert.ok(B.validate(net).valid);const before=JSON.stringify(net);for(const [a,b] of [['W','C'],['C','C'],['C','S']])assert.throws(()=>B.addEdge(net,a,b));assert.equal(JSON.stringify(net),before);B.addEdge(net,'S','R');assert.ok(B.topological(net));assert.equal(B.node(net,'R').cpt.length,4);assert.equal(B.validate(net).valid,false);B.deleteEdge(net,'S','R');assert.equal(B.node(net,'R').cpt.length,2);B.setStates(net,'C',['Sunny','Cloudy','Storm']);assert.equal(B.node(net,'C').cpt[0].p.length,3);assert.equal(B.node(net,'S').cpt.length,3);assert.equal(B.node(net,'R').cpt.length,3);assert.throws(()=>B.setStates(net,'C',['x','x']));const n=B.addNode(net);assert.equal(n.states.length,2);assert.equal(n.cpt[0].p[0],null)});
test('CPT validation requires coverage, finite bounded normalized rows and correct states',()=>{for(const invalid of [[-.1,1.1],[NaN,0],[.6,.6],[null,1],[Infinity,0]]){const net=B.preset();net.nodes[0].cpt[0].p=invalid;assert.equal(B.validate(net).valid,false);assert.throws(()=>B.inference(net,'C'))}const net=B.preset();net.nodes[3].cpt[1].given={...net.nodes[3].cpt[0].given};assert.equal(B.validate(net).valid,false);assert.equal(B.validate({nodes:[],edges:[]}).valid,false);const cyclic=B.preset();cyclic.edges.push({from:'W',to:'C'});assert.equal(B.validate(cyclic).dag,false)});
test('Factor restriction, multiplication and marginalization preserve exact probabilities',()=>{const net=B.preset('alarm'),fs=B.factors(net);assert.equal(fs[2].rows.length,8);const restricted=B.restrict(fs[2],{B:'True',E:'False'});assert.deepEqual(restricted.vars,['A']);close(restricted.rows[0].p,.94);const joint=B.multiply(fs);close(joint.rows.reduce((t,r)=>t+r.p,0),1);let marginal=joint;for(const id of ['B','E','J','M'])marginal=B.sumOut(marginal,id);close(marginal.rows.find(r=>r.a.A==='True').p,.002516442);assert.deepEqual(B.multiply([]),{vars:[],rows:[{a:{},p:1}]})});
test('Variable elimination matches independent enumeration for every query and multiple evidence scenarios',()=>{for(const name of ['weather','alarm']){const net=B.preset(name),evidenceSets=name==='alarm'?[{}, {B:'True',E:'False'},{J:'True',M:'True'},{A:'False',J:'True'}]:[{}, {W:'True'},{C:'False',R:'True'}];for(const e of evidenceSets)for(const n of net.nodes){const expected=enumerate(net,n.id,e),actual=finish(B.inference(net,n.id,e));close(actual.mass,expected.mass);actual.posterior.forEach((r,i)=>close(r.p,expected.p[i]));close(actual.posterior.reduce((t,r)=>t+r.p,0),1)}}close(B.posterior(B.preset('alarm'),'A',{B:'True',E:'False'}).posterior[0].p,.94);close(B.posterior(B.preset('alarm'),'B',{J:'True',M:'True'}).posterior[0].p,.2841718353643929)});
test('Construction format supports multistate variables, saved roundtrip, impossible evidence and observed query',()=>{const net={version:1,name:'Three states',nodes:[{id:'X',name:'X',states:['a','b','c'],x:100,y:100,cpt:[{given:{},p:[.2,.3,.5]}]},{id:'Y',name:'Y',states:['T','F'],x:200,y:200,cpt:[{given:{X:'a'},p:[1,0]},{given:{X:'b'},p:[.5,.5]},{given:{X:'c'},p:[0,1]}]}],edges:[{from:'X',to:'Y'}]};assert.ok(B.validate(net).valid);const result=B.posterior(B.clone(net),'X',{Y:'T'});close(result.posterior[0].p,4/7);close(result.posterior[1].p,3/7);close(B.posterior(net,'Y',{Y:'T'}).posterior[0].p,1);const impossible=B.posterior(net,'Y',{X:'a',Y:'F'});assert.equal(impossible.phase,'impossible');assert.equal(impossible.posterior,null);assert.equal(impossible.mass,0);assert.throws(()=>B.inference(net,'X',{Y:'unknown'}));assert.throws(()=>B.inference(net,'unknown'));});
test('Inference trace exposes separate factor operations and reset preserves network',()=>{const net=B.preset('alarm'),before=JSON.stringify(net),e=B.inference(net,'A',{B:'True',E:'False'});const s=finish(e),phases=s.trace.map(x=>x.phase);for(const p of ['construct','evidence','multiply','eliminate','query','normalize'])assert.ok(phases.includes(p));assert.equal(JSON.stringify(net),before);const reset=B.inference(net,'A',{}).snapshot();assert.equal(reset.done,false);assert.equal(reset.posterior,null);assert.equal(reset.trace.length,0)});
