const test=require('node:test'),assert=require('node:assert/strict');
const Q=require('../main/assets/phase8_labs/nqueens.js'),H=require('../main/assets/phase8_labs/hill-engine.js'),B=require('../main/assets/phase8_labs/local-beam-engine.js'),S=require('../main/assets/phase8_labs/sma-engine.js'),A=require('../main/assets/phase7_labs/astar-engine.js');
function finish(e,max=20000,inspect=()=>{}){let s=e.snapshot(),trace=[s];while(!s.done&&trace.length<max){s=e.step();inspect(s);trace.push(s)}assert.ok(s.done,'engine terminates');return {s,trace}}
function oracle(a){let h=0;for(let i=0;i<a.length;i++)for(let j=i+1;j<a.length;j++)if(a[i]===a[j]||a[i]+i===a[j]+j||a[i]-i===a[j]-j)h++;return h}
test('N-Queens counts attacking pairs once and generates immutable complete neighborhoods',()=>{assert.equal(Q.conflicts([1,3,0,2]),0);assert.equal(Q.conflicts([0,1,2,3]),6);for(let n of [4,5,6,8,10]){let rows=Q.initial(n),before=[...rows];assert.equal(Q.conflicts(rows),oracle(rows));let next=Q.neighbors(rows);assert.equal(next.length,n*(n-1));assert.equal(new Set(next.map(x=>x.key)).size,next.length);for(const x of next){assert.equal(x.h,oracle(x.rows));assert.equal(x.rows.filter((v,i)=>v!==rows[i]).length,1)}assert.deepEqual(rows,before)}assert.throws(()=>Q.neighbors([0,0,0,5]));});
test('Hill climbing chooses the globally best improving neighbor and reports exact deltas',()=>{for(let seed=1;seed<30;seed++){const initial=Q.initial(8,'random',seed),{s,trace}=finish(H.engine(initial,{maxIterations:100}));for(let i=1;i<trace.length;i++)if(['move','sideways'].includes(trace[i].phase)){assert.ok(trace[i].h<=trace[i-1].h);assert.equal(trace[i].h,Math.min(...trace[i-1].candidates.map(x=>x.h)))}for(let i=1;i<s.history.length;i++)assert.equal(s.history[i].delta,s.history[i].h-s.history[i-1].h);if(!s.found&&s.phase==='stuck')assert.ok(Q.neighbors(s.rows).every(x=>x.h>=s.h));assert.equal(s.found,s.h===0)}});
test('Hill sideways moves are bounded, restarts are explicit, and solved/reset states are correct',()=>{let sawSideways=false;for(let seed=1;seed<25;seed++){let {s,trace}=finish(H.engine(Q.initial(4,'random',seed),{sideways:true,sidewaysLimit:2,maxIterations:20}));sawSideways ||= trace.some(x=>x.phase==='sideways');assert.ok(trace.every(x=>x.sideways<=2));}assert.ok(sawSideways);const initial=[0,1,2,3],e=H.engine(initial,{stopAtOptimum:false,maxIterations:15});const {s}=finish(e);assert.ok(s.found||s.iteration===15);assert.deepEqual(H.engine(initial).snapshot().rows,initial);assert.equal(H.engine([1,3,0,2]).snapshot().found,true);});
test('Local Beam expands all members, deduplicates, ranks stably and replaces with true top-k',()=>{for(const k of [1,3,6]){const initial=B.initial(8,k,'random',2026),e=B.engine(initial,k,5),before=e.snapshot();let generated=e.step();const all=new Set(initial.flatMap(a=>Q.neighbors(a).map(x=>x.key)));assert.equal(generated.rawCount,k*56);assert.equal(generated.candidates.length,all.size);let ranked=e.step(),selected=e.step();assert.deepEqual(selected.selected.map(x=>x.id),ranked.candidates.slice(0,k).map(x=>x.id));assert.ok(ranked.candidates.every((x,i)=>!i||ranked.candidates[i-1].h<=x.h));const replaced=e.step();assert.deepEqual(replaced.beam.map(x=>x.key),selected.selected.map(x=>x.key));assert.deepEqual(before.beam.map(x=>x.rows).sort(),initial.sort());assert.equal(before.candidates.length,0);assert.equal(new Set(replaced.beam.map(x=>x.key)).size,k)}});
test('Local Beam recognizes generated solutions, stops cycles/limits and replays deterministically',()=>{const initial=[[1,3,0,0]],a=finish(B.engine(initial,1)),b=finish(B.engine(initial,1));assert.equal(a.s.found,true);assert.equal(Q.conflicts(a.s.best.rows),0);assert.deepEqual(a.trace,b.trace);assert.equal(B.engine([[1,3,0,2]],1).snapshot().found,true);assert.throws(()=>B.engine([[0,1,2,3],[0,1,2,3]],2));assert.ok(finish(B.engine(B.initial(8,3),3,3)).s.iteration<=3)});
test('SMA* enforces memory at every transition and matches A* with sufficient memory',()=>{const g=S.graph();for(const start of ['A','B','C'])for(const goal of g.nodes.map(n=>n.id)){const h=S.heuristics(g,goal),a=finish(A.engine(g,start,goal,h)).s;for(let m of [1,2,3,4,6,12]){const {s,trace}=finish(S.engine(g,start,goal,m,h),20000,x=>assert.ok(x.used<=m));if(m===12){assert.equal(s.found,a.found);if(s.found){assert.equal(s.cost,a.goalCost);assert.deepEqual(s.path,a.path)}}assert.ok(trace.every(x=>new Set(x.retained.map(n=>n.id)).size===x.used));for(let i=1;i<trace.length;i++)for(const n of trace[i].retained){const old=trace[i-1].retained.find(x=>x.id===n.id);if(old)assert.ok(n.f>=old.f)}}}});
test('SMA* forgets worst physical leaves, backs up costs, regenerates and clears state on reset',()=>{let regenerations=0,pruned=0;for(let seed=1;seed<30;seed++){const rand=Q.rng(seed),nodes=Array.from({length:15},(_,i)=>({id:'N'+i,h:0})),edges=nodes.slice(1).map((n,i)=>['N'+Math.floor(i/2),n.id,1+Math.floor(rand()*9)]),g={nodes,edges,directed:true},e=S.engine(g,'N0','N14',4),{s,trace}=finish(e);assert.equal(s.found,true);regenerations+=s.regenerations;pruned+=s.prunes;for(const snap of trace.filter(x=>x.phase==='memory')){const eligible=snap.retained.filter(x=>x.parent!=null&&x.id!==snap.pending.parent&&!snap.retained.some(n=>n.parent===x.id));const chosen=[...eligible,snap.pending].find(x=>x.id===snap.worst);assert.ok(eligible.every(x=>x.f<=chosen.f));}assert.equal(S.engine(g,'N0','N14',4).snapshot().prunes,0);assert.equal(S.engine(g,'N0','N14',15).snapshot().regenerations,0)}assert.ok(regenerations>0);assert.ok(pruned>0)});
test('SMA* validates tree/cost assumptions and reports insufficient memory without false solutions',()=>{const g=S.graph();assert.throws(()=>S.engine({...g,directed:false},'A','L'));assert.throws(()=>S.engine({...g,edges:[...g.edges,['B','C',1]]},'A','L'));assert.equal(finish(S.engine(g,'A','L',3)).s.found,false);assert.equal(finish(S.engine(g,'A','A',1)).s.cost,0);assert.ok(finish(S.engine(g,'A','L',4)).s.prunes>finish(S.engine(g,'A','L',12)).s.prunes)});
