package com.indianservers.ai_ml_dl_algorithms.ml_lab.learn

internal enum class DeepVisualization(val section: String, val title: String) {
    Perceptron("Neural Network Fundamentals", "Perceptron"),
    GradientDescent("Neural Network Fundamentals", "Gradient Descent"),
    Sgd("Neural Network Fundamentals", "Stochastic Gradient Descent"),
    MiniBatch("Neural Network Fundamentals", "Mini-Batch Gradient Descent"),
    Activations("Neural Network Fundamentals", "Activation Functions"),
    Loss("Neural Network Fundamentals", "Loss Functions"),
    WeightInit("Neural Network Fundamentals", "Weight Initialization"),
    BatchNorm("Neural Network Fundamentals", "Batch Normalization"),
    LayerNorm("Neural Network Fundamentals", "Layer Normalization"),
    Dropout("Neural Network Fundamentals", "Dropout"),
    Regularization("Neural Network Fundamentals", "Regularization"),
    Lenet("Convolutional Neural Networks", "LeNet"),
    Alexnet("Convolutional Neural Networks", "AlexNet"),
    Vgg("Convolutional Neural Networks", "VGG"),
    Inception("Convolutional Neural Networks", "GoogLeNet / Inception"),
    Resnet("Convolutional Neural Networks", "ResNet"),
    Densenet("Convolutional Neural Networks", "DenseNet"),
    Mobilenet("Convolutional Neural Networks", "MobileNet"),
    Efficientnet("Convolutional Neural Networks", "EfficientNet"),
    Convnext("Convolutional Neural Networks", "ConvNeXt"),
    Bidirectional("Sequence Models", "Bidirectional RNN"),
    Seq2Seq("Sequence Models", "Sequence-to-Sequence"),
    EncoderDecoder("Sequence Models", "Encoder-Decoder"),
    Bert("Transformers", "BERT"), Gpt("Transformers", "GPT-style Decoder Models"),
    T5("Transformers", "T5"), Vit("Transformers", "Vision Transformer"),
    Swin("Transformers", "Swin Transformer"),
    SparseAe("Autoencoders", "Sparse Autoencoder"),
    ConvAe("Autoencoders", "Convolutional Autoencoder"),
    Dcgan("Generative Models", "DCGAN"),
    ConditionalGan("Generative Models", "Conditional GAN"),
    CycleGan("Generative Models", "CycleGAN"),
    StyleGan("Generative Models", "StyleGAN"),
    Wgan("Generative Models", "Wasserstein GAN"),
    LatentDiffusion("Generative Models", "Latent Diffusion Models"),
    Gnn("Graph Neural Networks", "Graph Neural Network"),
    Gcn("Graph Neural Networks", "Graph Convolutional Network"),
    Gat("Graph Neural Networks", "Graph Attention Network"),
    GraphSage("Graph Neural Networks", "GraphSAGE"),
    GraphAe("Graph Neural Networks", "Graph Autoencoder");

    companion object { val byPlacement = entries.associateBy { it.section to it.title } }
}
